import { MnButton, MnButtonGroup } from './button';
import {
  MnAvatar,
  MnAvatarGroup,
  MnBadge,
  MnCard,
  MnCardContent,
  MnCardDescription,
  MnCardFooter,
  MnCardHeader,
  MnCardTitle,
  MnHeading,
  MnKbd,
  MnSeparator,
  MnTable,
  MnTableBody,
  MnTableCaption,
  MnTableCell,
  MnTableContainer,
  MnTableHead,
  MnTableHeader,
  MnTableRow,
} from './display';
import { MnAlert, MnProgress, MnProgressCircle, MnSkeleton, MnSpinner } from './feedback';
import {
  MnCheckbox,
  MnField,
  MnInput,
  MnInputGroup,
  MnRadio,
  MnRadioGroup,
  MnSelect,
  MnSlider,
  MnSwitch,
  MnTextarea,
} from './form';
import { MnIcon } from './icon';
import {
  MnAccordion,
  MnAccordionItem,
  MnBreadcrumb,
  MnPagination,
  MnTabs,
  MnTabsContent,
  MnTabsList,
  MnTabsTrigger,
} from './navigation';
import {
  MnDialog,
  MnDialogClose,
  MnDialogTrigger,
  MnMenu,
  MnMenuItem,
  MnMenuLabel,
  MnMenuSeparator,
  MnMenuTrigger,
  MnPopover,
  MnPopoverTrigger,
  MnToaster,
  MnTooltip,
} from './overlay';

/** Every Manthan directive and component: `imports: [MN_COMPONENTS]`. */
export const MN_COMPONENTS = [
  MnIcon,
  MnButton,
  MnButtonGroup,
  MnBadge,
  MnAvatar,
  MnAvatarGroup,
  MnCard,
  MnCardHeader,
  MnCardTitle,
  MnCardDescription,
  MnCardContent,
  MnCardFooter,
  MnKbd,
  MnSeparator,
  MnHeading,
  MnTableContainer,
  MnTable,
  MnTableHeader,
  MnTableBody,
  MnTableRow,
  MnTableHead,
  MnTableCell,
  MnTableCaption,
  MnField,
  MnInput,
  MnInputGroup,
  MnTextarea,
  MnSlider,
  MnSelect,
  MnCheckbox,
  MnSwitch,
  MnRadioGroup,
  MnRadio,
  MnTabs,
  MnTabsList,
  MnTabsTrigger,
  MnTabsContent,
  MnAccordion,
  MnAccordionItem,
  MnBreadcrumb,
  MnPagination,
  MnDialog,
  MnDialogTrigger,
  MnDialogClose,
  MnPopover,
  MnPopoverTrigger,
  MnMenu,
  MnMenuTrigger,
  MnMenuItem,
  MnMenuLabel,
  MnMenuSeparator,
  MnTooltip,
  MnToaster,
  MnAlert,
  MnProgress,
  MnProgressCircle,
  MnSpinner,
  MnSkeleton,
] as const;
